export type AlphaSuggestionSections = {
  phrases: string[];
  words: string[];
  daily: string[];
  sentences: string[];
};

export const getAlphaSuggestions = (ch: string): AlphaSuggestionSections | null => {
  switch ((ch || '').toUpperCase()) {
    case 'A':
      return {
        phrases: [
          "At all",
          "As soon as",
          "After all",
          "At first",
          "As long as",
          "As per schedule",
          "At your convenience",
          "As discussed",
          "As mentioned earlier",
          "At this moment",
        ],
        words: [
          "Apple",
          "Ant",
          "At",
          "Ask",
          "Arm",
          "Area",
          "Able",
          "Age",
          "Any",
          "Act",
          "Agenda",
          "Analysis",
          "Assignment",
          "Agreement",
          "Approval",
          "Application",
          "Appointment",
          "Achievement",
          "Attention",
          "Action",
        ],
        daily: [
          "Appointment",
          "Alert",
          "Access",
          "Application",
          "Address",
          "Answer",
          "Amount",
          "Area",
          "Assist",
          "Arrange",
          "Attend",
          "Arrive",
          "Apologize",
          "Ask for help",
          "Accept invitation",
          "Adjust schedule",
          "Attend meeting",
          "Apply leave",
          "Add contact",
          "Arrange transport",
        ],
        sentences: [
          "I am fine",
          "Are you okay?",
          "All is well",
          "Ask me later",
          "At your service",
          "I am available for work",
          "All assignments are complete",
          "Are you attending the meeting?",
          "Apply for the job",
          "All tasks are approved",
        ],
      };
    case 'B':
      return {
        phrases: [
          "Be careful",
          "Be right back",
          "By the way",
          "Be kind to others",
          "Be on time",
          "Be confident",
          "Be professional",
          "Be honest",
          "Be positive",
          "By all means",
        ],
        words: [
          "Book",
          "Bag",
          "Ball",
          "Bank",
          "Begin",
          "Build",
          "Buy",
          "Bring",
          "Business",
          "Balance",
          "Budget",
          "Boss",
          "Break",
          "Benefit",
          "Belief",
          "Background",
          "Branch",
          "Bill",
          "Bonus",
          "Browser",
        ],
        daily: [
          "Breakfast",
          "Bus",
          "Bank",
          "Bill",
          "Button",
          "Borrow",
          "Buy ticket",
          "Book appointment",
          "Bring file",
          "Balance account",
          "Backup data",
          "Begin meeting",
          "Break time",
          "Backup plan",
          "Build idea",
          "Borrow pen",
          "Buy groceries",
          "Be ready",
          "Be on call",
          "Be focused",
        ],
        sentences: [
          "Be happy always",
          "Bring the document",
          "Buy the items",
          "Be ready for the class",
          "Book your slot",
          "Be kind to customers",
          "Begin the presentation",
          "Be honest in work",
          "Balance your time",
          "Be careful while driving",
        ],
      };
    case 'C':
      return {
        phrases: [
          "Call me back",
          "Catch up soon",
          "Check your mail",
          "Come here",
          "Can you help?",
          "Clear the screen",
          "Check attendance",
          "Create report",
          "Call the client",
          "Check availability",
        ],
        words: [
          "Cat",
          "Car",
          "Chair",
          "Class",
          "Code",
          "Computer",
          "Camera",
          "Client",
          "Clock",
          "College",
          "Company",
          "Check",
          "Confirm",
          "Call",
          "Chat",
          "Course",
          "Create",
          "Connect",
          "Calendar",
          "Cancel",
        ],
        daily: [
          "Call teacher",
          "Check homework",
          "Clean table",
          "Complete work",
          "Charge phone",
          "Cook food",
          "Copy notes",
          "Catch bus",
          "Close door",
          "Count money",
          "Create account",
          "Check report",
          "Change clothes",
          "Confirm booking",
          "Carry bag",
          "Cut paper",
          "Connect WiFi",
          "Call manager",
          "Check battery",
          "Contact support",
        ],
        sentences: [
          "Can you help me?",
          "Call the doctor",
          "Check your phone",
          "Come to office",
          "Close the window",
          "Create your profile",
          "Confirm the meeting",
          "Check your message",
          "Call me after class",
          "Cancel the order",
        ],
      };
    case 'D':
      return {
        phrases: [
          "Do it now",
          "Don’t worry",
          "Drive safe",
          "Don’t forget",
          "Do your best",
          "Don’t be late",
          "Deal with care",
          "Do not disturb",
          "Discuss later",
          "Do your duty",
        ],
        words: [
          "Dog",
          "Door",
          "Day",
          "Date",
          "Doctor",
          "Drive",
          "Deliver",
          "Data",
          "Desk",
          "Device",
          "Development",
          "Design",
          "Download",
          "Document",
          "Decision",
          "Department",
          "Dashboard",
          "Deadline",
          "Director",
          "Duty",
        ],
        daily: [
          "Drink water",
          "Do homework",
          "Drive slowly",
          "Deliver parcel",
          "Download app",
          "Discuss project",
          "Do laundry",
          "Dust table",
          "Design poster",
          "Draw picture",
          "Deliver report",
          "Do payment",
          "Develop idea",
          "Document file",
          "Do meeting",
          "Donate clothes",
          "Dress properly",
          "Display chart",
          "Deal with client",
          "Do revision",
        ],
        sentences: [
          "Do your homework",
          "Don’t worry about it",
          "Drive carefully",
          "Do not forget the file",
          "Deliver this message",
          "Discuss the project tomorrow",
          "Download the presentation",
          "Doctor is available",
          "Do your duty sincerely",
          "Do it with confidence",
        ],
      };
    case 'E':
      return {
        phrases: [
          "Each day",
          "Every time",
          "Even now",
          "End of day",
          "Enough for today",
          "Every week",
          "Easy to use",
          "Everything okay",
          "Every morning",
          "Every person",
        ],
        words: [
          "Elephant",
          "Ear",
          "Eye",
          "Egg",
          "Eat",
          "End",
          "Energy",
          "Engineer",
          "Email",
          "Exam",
          "Event",
          "Education",
          "Employee",
          "Effort",
          "Experience",
          "Equipment",
          "Emergency",
          "Entry",
          "Environment",
          "Estimate",
        ],
        daily: [
          "Eat breakfast",
          "Enter class",
          "Email teacher",
          "Enjoy weekend",
          "Exercise daily",
          "Edit file",
          "Enroll course",
          "Explain topic",
          "Examine report",
          "End meeting",
          "Enjoy break",
          "Edit photo",
          "Enable sound",
          "Express idea",
          "Evaluate test",
          "Exit room",
          "Engage user",
          "Extend deadline",
          "Earn respect",
          "Explain situation",
        ],
        sentences: [
          "Eat your food",
          "Enjoy your day",
          "Enter the meeting room",
          "End the task on time",
          "Email the report",
          "Explain your point clearly",
          "Engineer fixed the issue",
          "Every person matters",
          "Exercise is important",
          "Everything is fine",
        ],
      };
    case 'F':
      return {
        phrases: [
          "For now",
          "For sure",
          "From here",
          "Follow up",
          "Feel free",
          "For example",
          "First of all",
          "For your info",
          "For the record",
          "From my side",
        ],
        words: [
          "Food",
          "Fine",
          "Friend",
          "Family",
          "Feel",
          "Fast",
          "Find",
          "Fix",
          "Fun",
          "Future",
        ],
        daily: [
          "Fill form",
          "Follow plan",
          "Finish task",
          "Fold clothes",
          "Feed pets",
          "Find keys",
          "Fix issue",
          "Face time",
          "Fetch water",
          "Finalize work",
        ],
        sentences: [
          "I feel fine",
          "Find my phone",
          "Finish your work",
          "Follow the rules",
          "For your help, thanks",
          "Family is important",
          "Friends are coming",
          "Fix the problem",
          "Food is ready",
          "For now, that's all",
        ],
      };
    case 'G':
      return {
        phrases: [
          "Good morning",
          "Good evening",
          "Go ahead",
          "Get ready",
          "Give me",
          "Go right now",
          "Great job",
          "Good to go",
          "Get back soon",
          "Going well",
        ],
        words: [
          "Good",
          "Go",
          "Give",
          "Get",
          "Great",
          "Group",
          "Game",
          "Goal",
          "Guide",
          "Green",
        ],
        daily: [
          "Go outside",
          "Get groceries",
          "Give feedback",
          "Go to school",
          "Get water",
          "Grab lunch",
          "Go home",
          "Get invoice",
          "Give thanks",
          "Go early",
        ],
        sentences: [
          "Good morning to you",
          "Go and get it",
          "Give me a minute",
          "Get ready for class",
          "Great job today",
          "Good to see you",
          "Go straight ahead",
          "Get well soon",
          "Give it back",
          "Going to the market",
        ],
      };
    case 'H':
      return {
        phrases: [
          "Hello there",
          "How are you",
          "Have a seat",
          "Hold on",
          "Hang on",
          "Happy to help",
          "Hope you’re well",
          "Here you go",
          "Head this way",
          "Have a nice day",
        ],
        words: [
          "Hello",
          "Help",
          "Have",
          "Here",
          "Hold",
          "Happy",
          "Home",
          "Hope",
          "Hand",
          "Hear",
        ],
        daily: [
          "Have breakfast",
          "Help others",
          "Hold door",
          "Head home",
          "Hear music",
          "Hang clothes",
          "Have water",
          "Have lunch",
          "Help at work",
          "Have rest",
        ],
        sentences: [
          "Hello, how are you",
          "Happy to help you",
          "Here is your file",
          "Hold on a second",
          "Have a great day",
          "Head to the office",
          "Hope you get well",
          "Have you eaten",
          "Help me with this",
          "Here we go now",
        ],
      };
    case 'I':
      return {
        phrases: [
          "I am here",
          "In a minute",
          "It is fine",
          "I will go",
          "I need help",
          "I am ready",
          "I can try",
          "In the morning",
          "I am okay",
          "I will call",
        ],
        words: [
          "I",
          "Is",
          "It",
          "In",
          "If",
          "Idea",
          "Important",
          "Information",
          "Invite",
          "Improve",
        ],
        daily: [
          "I am busy",
          "In office",
          "I will come",
          "In a while",
          "I will wait",
          "I will check",
          "In progress",
          "I will pay",
          "I will help",
          "I will write",
        ],
        sentences: [
          "I am fine",
          "I need help",
          "It is okay",
          "I will do it",
          "I am on the way",
          "I am at home",
          "I will call you",
          "I will be there",
          "I can help you",
          "I am learning",
        ],
      };
    case 'K':
      return {
        phrases: [
          "Keep going",
          "Kind regards",
          "Keep in touch",
          "Keep it up",
          "Know this",
          "Keep safe",
          "Kind words",
          "Keep waiting",
          "Keep calm",
          "Keep trying",
        ],
        words: [
          "Keep",
          "Kind",
          "Know",
          "Key",
          "Kids",
          "Kitchen",
          "Knowledge",
          "Keyboard",
          "Kit",
          "Kite",
        ],
        daily: [
          "Keep notes",
          "Keep keys",
          "Keep record",
          "Keep track",
          "Know schedule",
          "Keep distance",
          "Keep documents",
          "Keep door locked",
          "Keep phone charged",
          "Keep wallet safe",
        ],
        sentences: [
          "Keep going, you can do it",
          "Kindly close the door",
          "Keep your phone charged",
          "Keep this document safe",
          "Know the meeting time",
          "Keep calm and proceed",
          "Keep the volume low",
          "Keep me informed",
          "Keep the place clean",
          "Keep working on this",
        ],
      };
    case 'J':
      return {
        phrases: [
          "Just a moment",
          "Just in case",
          "Join us",
          "Just now",
          "Jump in",
          "Just right",
          "Join the team",
          "Just like that",
          "Join meeting",
          "Just wait",
        ],
        words: [
          "Just",
          "Join",
          "Jump",
          "Job",
          "Joy",
          "Judge",
          "Journal",
          "Journey",
          "Joke",
          "Jacket",
          "Jewelry",
          "Juice",
          "Junior",
          "Justice",
          "January",
          "Jogging",
          "Jigsaw",
          "Jelly",
          "Jungle",
          "Junction",
        ],
        daily: [
          "Join class",
          "Just relax",
          "Jump start",
          "Join meeting",
          "Just check",
          "Join group",
          "Just finish",
          "Join call",
          "Just confirm",
          "Join team",
          "Just update",
          "Join session",
          "Just review",
          "Join event",
          "Just verify",
          "Join discussion",
          "Just submit",
          "Join workshop",
          "Just approve",
          "Join webinar",
        ],
        sentences: [
          "Just a minute please",
          "Join us for lunch",
          "Just wait here",
          "Join the meeting now",
          "Just check your email",
          "Join the group chat",
          "Just finish your work",
          "Join the call at 3 PM",
          "Just confirm the booking",
          "Join the team meeting",
        ],
      };
    case 'L':
      return {
        phrases: [
          "Let's go",
          "Look here",
          "Listen please",
          "Long time",
          "Leave now",
          "Log in",
          "Let me know",
          "Love this",
          "Learn more",
          "Last time",
        ],
        words: [
          "Let",
          "Look",
          "Listen",
          "Learn",
          "Live",
          "Leave",
          "Love",
          "Light",
          "Letter",
          "List",
        ],
        daily: [
          "Leave early",
          "Lock door",
          "Light on",
          "Lunch time",
          "Laundry day",
          "Learn topic",
          "List items",
          "Log meeting",
          "Limit speed",
          "Look outside",
        ],
        sentences: [
          "Let's go now",
          "Look at this",
          "Listen to me",
          "Learn this lesson",
          "Leave the room",
          "Love your work",
          "Let me help you",
          "Log in to account",
          "Last time we met",
          "Light the candle",
        ],
      };
    case 'M':
      return {
        phrases: [
          "More please",
          "Meet me",
          "Make sure",
          "Move forward",
          "My pleasure",
          "Much better",
          "Meet later",
          "Make it happen",
          "Move ahead",
          "Much thanks",
        ],
        words: [
          "More",
          "Meet",
          "Make",
          "Move",
          "Much",
          "Many",
          "Money",
          "Month",
          "Morning",
          "Message",
          "Manager",
          "Meeting",
          "Market",
          "Mobile",
          "Method",
          "Matter",
          "Member",
          "Memory",
          "Moment",
          "Master",
        ],
        daily: [
          "Meet friend",
          "Make coffee",
          "Move files",
          "Make call",
          "Meet client",
          "Make plan",
          "Move items",
          "Make list",
          "Meet teacher",
          "Make report",
          "Move forward",
          "Make decision",
          "Meet deadline",
          "Make payment",
          "Move quickly",
          "Make appointment",
          "Meet requirement",
          "Make progress",
          "Move carefully",
          "Make reservation",
        ],
        sentences: [
          "Meet me at the office",
          "Make sure to attend",
          "Move forward with plan",
          "More information needed",
          "Meet the deadline today",
          "Make a good impression",
          "Move the meeting to tomorrow",
          "Much better than before",
          "Meet me after class",
          "Make it happen soon",
        ],
      };
    case 'N':
      return {
        phrases: [
          "No problem",
          "Not now",
          "Next time",
          "No worries",
          "Not yet",
          "Need help",
          "No thanks",
          "Next week",
          "Not sure",
          "Need more",
        ],
        words: [
          "No",
          "Not",
          "Now",
          "New",
          "Need",
          "Next",
          "Name",
          "Note",
          "Number",
          "Night",
          "Network",
          "Notice",
          "Nature",
          "Normal",
          "Nation",
          "Necessary",
          "Neighbor",
          "Nurse",
          "News",
          "November",
        ],
        daily: [
          "Note down",
          "Need help",
          "Next meeting",
          "New project",
          "Need time",
          "Next step",
          "Note reminder",
          "Need support",
          "Next class",
          "New update",
          "Note important",
          "Need approval",
          "Next deadline",
          "New feature",
          "Need confirmation",
          "Next session",
          "Note details",
          "Need information",
          "Next appointment",
          "New assignment",
        ],
        sentences: [
          "No problem at all",
          "Not now, maybe later",
          "Next time we meet",
          "No worries, I'll help",
          "Need help with this",
          "Not sure about that",
          "Next week is fine",
          "No thanks, I'm good",
          "Need more information",
          "Not yet, wait please",
        ],
      };
    case 'O':
      return {
        phrases: [
          "Of course",
          "On time",
          "On the way",
          "One moment",
          "Open now",
          "On schedule",
          "On my way",
          "One more",
          "On it",
          "Open door",
        ],
        words: [
          "Of",
          "On",
          "One",
          "Open",
          "Only",
          "Other",
          "Order",
          "Office",
          "Option",
          "Online",
          "Object",
          "Offer",
          "Opportunity",
          "Organization",
          "Operation",
          "Owner",
          "Outcome",
          "Outline",
          "Output",
          "Overtime",
        ],
        daily: [
          "Open file",
          "On time",
          "Order food",
          "Open door",
          "One more",
          "On schedule",
          "Open app",
          "Order items",
          "On the way",
          "Open window",
          "Order ticket",
          "On break",
          "Open account",
          "Order coffee",
          "On call",
          "Open meeting",
          "Order supplies",
          "On leave",
          "Open document",
          "Order lunch",
        ],
        sentences: [
          "Of course, I'll help",
          "On time for meeting",
          "One moment please",
          "Open the door now",
          "On my way to office",
          "One more thing to do",
          "On schedule as planned",
          "Open your email",
          "Order the items now",
          "On the way home",
        ],
      };
    case 'P':
      return {
        phrases: [
          "Please wait",
          "Pick up",
          "Put down",
          "Pay now",
          "Play music",
          "Please help",
          "Pick me up",
          "Put it here",
          "Please come",
          "Pick this",
        ],
        words: [
          "Please",
          "Pick",
          "Put",
          "Pay",
          "Play",
          "Phone",
          "Paper",
          "People",
          "Place",
          "Plan",
          "Project",
          "Program",
          "Process",
          "Product",
          "Payment",
          "Person",
          "Picture",
          "Point",
          "Price",
          "Problem",
        ],
        daily: [
          "Pick file",
          "Pay bill",
          "Put away",
          "Play music",
          "Pick up",
          "Pay rent",
          "Put back",
          "Play video",
          "Pick items",
          "Pay fee",
          "Put order",
          "Play game",
          "Pick time",
          "Pay tax",
          "Put together",
          "Play song",
          "Pick date",
          "Pay salary",
          "Put forward",
          "Play audio",
        ],
        sentences: [
          "Please wait a moment",
          "Pick up the phone",
          "Put it on the table",
          "Pay the bill now",
          "Play some music",
          "Please help me",
          "Pick me up at 5 PM",
          "Put the file here",
          "Please come here",
          "Pick this option",
        ],
      };
    case 'Q':
      return {
        phrases: [
          "Quick question",
          "Quite right",
          "Quality first",
          "Quick check",
          "Quite good",
          "Quick reply",
          "Quality work",
          "Quick update",
          "Quite sure",
          "Quick fix",
        ],
        words: [
          "Quick",
          "Quite",
          "Quality",
          "Question",
          "Quiet",
          "Quit",
          "Quote",
          "Quarter",
          "Queue",
          "Quiz",
          "Qualify",
          "Quantity",
          "Query",
          "Quest",
          "Quota",
          "Quotation",
          "Qualification",
          "Quarterly",
          "Quietly",
          "Quicker",
        ],
        daily: [
          "Quick check",
          "Quality check",
          "Quick reply",
          "Question answer",
          "Quick update",
          "Quality work",
          "Quick fix",
          "Question mark",
          "Quick review",
          "Quality control",
          "Quick response",
          "Quality assurance",
          "Quick decision",
          "Question time",
          "Quick meeting",
          "Quality standard",
          "Quick access",
          "Question session",
          "Quick solution",
          "Quality check",
        ],
        sentences: [
          "Quick question for you",
          "Quite right about that",
          "Quality is important",
          "Quick check needed",
          "Quite good progress",
          "Quick reply please",
          "Quality work matters",
          "Quick update on status",
          "Quite sure it's correct",
          "Quick fix required",
        ],
      };
    case 'R':
      return {
        phrases: [
          "Right away",
          "Read this",
          "Run fast",
          "Right now",
          "Read carefully",
          "Run quickly",
          "Right here",
          "Read aloud",
          "Run smoothly",
          "Right on time",
        ],
        words: [
          "Right",
          "Read",
          "Run",
          "Room",
          "Road",
          "Rule",
          "Report",
          "Result",
          "Review",
          "Request",
          "Record",
          "Resource",
          "Response",
          "Reason",
          "Rate",
          "Range",
          "Risk",
          "Role",
          "Round",
          "Return",
        ],
        daily: [
          "Read email",
          "Run errand",
          "Right time",
          "Read document",
          "Run meeting",
          "Right place",
          "Read message",
          "Run program",
          "Right answer",
          "Read report",
          "Run test",
          "Right direction",
          "Read notes",
          "Run check",
          "Right decision",
          "Read article",
          "Run update",
          "Right approach",
          "Read manual",
          "Run analysis",
        ],
        sentences: [
          "Right away, I'll do it",
          "Read this document",
          "Run fast to catch up",
          "Right now is perfect",
          "Read carefully please",
          "Run quickly to finish",
          "Right here is fine",
          "Read aloud clearly",
          "Run smoothly today",
          "Right on time as usual",
        ],
      };
    case 'S':
      return {
        phrases: [
          "See you",
          "Stay safe",
          "Send it",
          "See later",
          "Stay here",
          "Send now",
          "See soon",
          "Stay calm",
          "Send email",
          "See tomorrow",
        ],
        words: [
          "See",
          "Stay",
          "Send",
          "Say",
          "Show",
          "Start",
          "Stop",
          "Study",
          "Save",
          "Share",
          "Schedule",
          "System",
          "Service",
          "Student",
          "Subject",
          "Support",
          "Success",
          "Solution",
          "Session",
          "Status",
        ],
        daily: [
          "Send email",
          "Stay home",
          "See friend",
          "Send message",
          "Stay focused",
          "See doctor",
          "Send report",
          "Stay healthy",
          "See teacher",
          "Send file",
          "Stay positive",
          "See client",
          "Send invoice",
          "Stay alert",
          "See manager",
          "Send reminder",
          "Stay updated",
          "See colleague",
          "Send notification",
          "Stay connected",
        ],
        sentences: [
          "See you tomorrow",
          "Stay safe always",
          "Send it now please",
          "See later today",
          "Stay here with me",
          "Send now to client",
          "See soon at office",
          "Stay calm and relax",
          "Send email to team",
          "See tomorrow morning",
        ],
      };
    case 'T':
      return {
        phrases: [
          "Thank you",
          "Take care",
          "Try again",
          "Tell me",
          "Take time",
          "Try this",
          "Tell us",
          "Take it",
          "Try now",
          "Tell them",
        ],
        words: [
          "Thank",
          "Take",
          "Try",
          "Tell",
          "Time",
          "Today",
          "Tomorrow",
          "Team",
          "Task",
          "Test",
          "Topic",
          "Table",
          "Teacher",
          "Ticket",
          "Travel",
          "Training",
          "Transfer",
          "Transaction",
          "Treatment",
          "Trouble",
        ],
        daily: [
          "Take break",
          "Try again",
          "Tell story",
          "Take photo",
          "Try method",
          "Tell truth",
          "Take notes",
          "Try solution",
          "Tell details",
          "Take action",
          "Try approach",
          "Tell facts",
          "Take decision",
          "Try option",
          "Tell information",
          "Take responsibility",
          "Try technique",
          "Tell experience",
          "Take opportunity",
          "Try strategy",
        ],
        sentences: [
          "Thank you very much",
          "Take care of yourself",
          "Try again tomorrow",
          "Tell me the truth",
          "Take time to think",
          "Try this method",
          "Tell us your plan",
          "Take it easy",
          "Try now if possible",
          "Tell them the news",
        ],
      };
    case 'U':
      return {
        phrases: [
          "Use this",
          "Up to you",
          "Use it",
          "Up there",
          "Use now",
          "Up here",
          "Use carefully",
          "Up ahead",
          "Use properly",
          "Up next",
        ],
        words: [
          "Use",
          "Up",
          "Us",
          "User",
          "Unit",
          "Update",
          "Upload",
          "Understand",
          "University",
          "Until",
          "Urgent",
          "Usage",
          "Utility",
          "Universe",
          "Uniform",
          "Union",
          "Unique",
          "Unity",
          "Unlock",
          "Upgrade",
        ],
        daily: [
          "Use app",
          "Update status",
          "Upload file",
          "Use tool",
          "Update profile",
          "Upload photo",
          "Use system",
          "Update information",
          "Upload document",
          "Use feature",
          "Update schedule",
          "Upload video",
          "Use method",
          "Update record",
          "Upload data",
          "Use option",
          "Update details",
          "Upload image",
          "Use service",
          "Update progress",
        ],
        sentences: [
          "Use this tool carefully",
          "Up to you to decide",
          "Use it properly",
          "Up there on the shelf",
          "Use now if needed",
          "Up here in the office",
          "Use carefully please",
          "Up ahead is the exit",
          "Use properly as instructed",
          "Up next is your turn",
        ],
      };
    case 'V':
      return {
        phrases: [
          "Very good",
          "Visit us",
          "Very well",
          "Visit here",
          "Very nice",
          "Visit today",
          "Very much",
          "Visit soon",
          "Very helpful",
          "Visit again",
        ],
        words: [
          "Very",
          "Visit",
          "View",
          "Video",
          "Voice",
          "Value",
          "Version",
          "Vehicle",
          "Village",
          "Vision",
          "Volume",
          "Vote",
          "Voucher",
          "Virus",
          "Vacation",
          "Variety",
          "Vendor",
          "Venue",
          "Venture",
          "Victory",
        ],
        daily: [
          "Visit friend",
          "View report",
          "Visit doctor",
          "View document",
          "Visit client",
          "View profile",
          "Visit office",
          "View details",
          "Visit home",
          "View status",
          "Visit store",
          "View results",
          "Visit website",
          "View progress",
          "Visit place",
          "View information",
          "Visit location",
          "View data",
          "Visit site",
          "View update",
        ],
        sentences: [
          "Very good work today",
          "Visit us tomorrow",
          "Very well done",
          "Visit here next week",
          "Very nice to meet",
          "Visit today if possible",
          "Very much appreciated",
          "Visit soon please",
          "Very helpful advice",
          "Visit again next time",
        ],
      };
    case 'W':
      return {
        phrases: [
          "Welcome back",
          "Wait here",
          "Work hard",
          "Wait please",
          "Work together",
          "Wait a moment",
          "Work well",
          "Wait for me",
          "Work fast",
          "Wait outside",
        ],
        words: [
          "Welcome",
          "Wait",
          "Work",
          "Want",
          "Will",
          "Way",
          "Week",
          "Water",
          "World",
          "Word",
          "Website",
          "Workshop",
          "Warning",
          "Warranty",
          "Weather",
          "Weight",
          "Window",
          "Winner",
          "Witness",
          "Worker",
        ],
        daily: [
          "Work hard",
          "Wait here",
          "Work smart",
          "Wait outside",
          "Work together",
          "Wait for call",
          "Work fast",
          "Wait patiently",
          "Work carefully",
          "Wait for reply",
          "Work efficiently",
          "Wait for approval",
          "Work diligently",
          "Wait for confirmation",
          "Work properly",
          "Wait for response",
          "Work effectively",
          "Wait for update",
          "Work smoothly",
          "Wait for decision",
        ],
        sentences: [
          "Welcome back to office",
          "Wait here please",
          "Work hard and succeed",
          "Wait please, I'm coming",
          "Work together as team",
          "Wait a moment longer",
          "Work well with others",
          "Wait for me outside",
          "Work fast to finish",
          "Wait outside the room",
        ],
      };
    case 'X':
      return {
        phrases: [
          "X marks spot",
          "X factor",
          "X amount",
          "X times",
          "X number",
          "X value",
          "X axis",
          "X coordinate",
          "X position",
          "X location",
        ],
        words: [
          "X",
          "X-ray",
          "X-axis",
          "X-factor",
          "Xerox",
          "Xenon",
          "Xylophone",
          "Xenophobia",
          "Xerography",
          "Xerophyte",
        ],
        daily: [
          "X check",
          "X verify",
          "X confirm",
          "X validate",
          "X review",
          "X examine",
          "X inspect",
          "X analyze",
          "X test",
          "X measure",
        ],
        sentences: [
          "X marks the spot",
          "X factor is important",
          "X amount is needed",
          "X times better",
          "X number of items",
          "X value is correct",
          "X axis is horizontal",
          "X coordinate is set",
          "X position is fixed",
          "X location is found",
        ],
      };
    case 'Y':
      return {
        phrases: [
          "Yes please",
          "You are right",
          "Yes sure",
          "You can do it",
          "Yes of course",
          "You are welcome",
          "Yes I will",
          "You are great",
          "Yes I can",
          "You are amazing",
        ],
        words: [
          "Yes",
          "You",
          "Your",
          "Year",
          "Yesterday",
          "Young",
          "Yellow",
          "Yield",
          "Yard",
          "Youth",
          "Yearly",
          "Yoga",
          "Yogurt",
          "Yacht",
          "Yawn",
          "Yell",
          "Yet",
          "Yolk",
          "Yonder",
          "Yummy",
        ],
        daily: [
          "Yes I will",
          "You can try",
          "Yes I can",
          "You should go",
          "Yes I agree",
          "You need help",
          "Yes I understand",
          "You are right",
          "Yes I know",
          "You are welcome",
          "Yes I see",
          "You can start",
          "Yes I accept",
          "You can finish",
          "Yes I confirm",
          "You can proceed",
          "Yes I approve",
          "You can continue",
          "Yes I support",
          "You can succeed",
        ],
        sentences: [
          "Yes please, go ahead",
          "You are right about that",
          "Yes sure, I'll help",
          "You can do it easily",
          "Yes of course, no problem",
          "You are welcome here",
          "Yes I will come",
          "You are great at this",
          "Yes I can help",
          "You are amazing person",
        ],
      };
    case 'Z':
      return {
        phrases: [
          "Zoom in",
          "Zero error",
          "Zoom out",
          "Zero delay",
          "Zip file",
          "Zero tolerance",
          "Zone area",
          "Zero waste",
          "Zest for life",
          "Zero risk",
        ],
        words: [
          "Zoom",
          "Zero",
          "Zip",
          "Zone",
          "Zest",
          "Zebra",
          "Zenith",
          "Zeal",
          "Zephyr",
          "Zinc",
          "Zipper",
          "Zodiac",
          "Zombie",
          "Zoo",
          "Zucchini",
          "Zigzag",
          "Zillion",
          "Zircon",
          "Zither",
          "Zonal",
        ],
        daily: [
          "Zoom meeting",
          "Zero errors",
          "Zip folder",
          "Zone check",
          "Zoom call",
          "Zero mistakes",
          "Zip file",
          "Zone area",
          "Zoom session",
          "Zero issues",
          "Zip archive",
          "Zone limit",
          "Zoom video",
          "Zero problems",
          "Zip document",
          "Zone access",
          "Zoom audio",
          "Zero defects",
          "Zip package",
          "Zone control",
        ],
        sentences: [
          "Zoom in to see details",
          "Zero error in code",
          "Zoom out to view all",
          "Zero delay in response",
          "Zip file before sending",
          "Zero tolerance policy",
          "Zone area is restricted",
          "Zero waste initiative",
          "Zest for life is important",
          "Zero risk approach",
        ],
      };
    case '0':
      return {
        phrases: [
          "Zero errors",
          "Zero delay",
          "Zero tolerance",
          "Zero waste",
          "Zero risk",
          "Zero defects",
          "Zero problems",
          "Zero issues",
          "Zero mistakes",
          "Zero downtime",
        ],
        words: [
          "Zero",
          "Zilch",
          "Nought",
          "Nothing",
          "Null",
          "None",
          "Nil",
          "Naught",
          "O",
          "Cipher",
        ],
        daily: [
          "Zero errors today",
          "Zero delay expected",
          "Zero tolerance policy",
          "Zero waste goal",
          "Zero risk approach",
          "Zero defects found",
          "Zero problems reported",
          "Zero issues detected",
          "Zero mistakes made",
          "Zero downtime achieved",
        ],
        sentences: [
          "Zero errors in the code",
          "Zero delay in delivery",
          "Zero tolerance for mistakes",
          "Zero waste is our goal",
          "Zero risk in this plan",
          "Zero defects in product",
          "Zero problems so far",
          "Zero issues to report",
          "Zero mistakes allowed",
          "Zero downtime maintained",
        ],
      };
    case '1':
      return {
        phrases: [
          "One moment",
          "One more",
          "One time",
          "One way",
          "One day",
          "One step",
          "One click",
          "One hour",
          "One week",
          "One month",
        ],
        words: [
          "One",
          "First",
          "Single",
          "Once",
          "Unit",
          "Unity",
          "Unique",
          "Unite",
          "Unified",
          "Unison",
        ],
        daily: [
          "One task",
          "One meeting",
          "One call",
          "One email",
          "One file",
          "One report",
          "One update",
          "One check",
          "One review",
          "One approval",
        ],
        sentences: [
          "One moment please",
          "One more thing",
          "One time only",
          "One way street",
          "One day at a time",
          "One step forward",
          "One click away",
          "One hour meeting",
          "One week deadline",
          "One month project",
        ],
      };
    case '2':
      return {
        phrases: [
          "Two times",
          "Two ways",
          "Two days",
          "Two weeks",
          "Two hours",
          "Two steps",
          "Two options",
          "Two minutes",
          "Two people",
          "Two items",
        ],
        words: [
          "Two",
          "Second",
          "Double",
          "Pair",
          "Twin",
          "Dual",
          "Duo",
          "Couple",
          "Binary",
          "Both",
        ],
        daily: [
          "Two tasks",
          "Two meetings",
          "Two calls",
          "Two emails",
          "Two files",
          "Two reports",
          "Two updates",
          "Two checks",
          "Two reviews",
          "Two approvals",
        ],
        sentences: [
          "Two times better",
          "Two ways to solve",
          "Two days remaining",
          "Two weeks notice",
          "Two hours meeting",
          "Two steps ahead",
          "Two options available",
          "Two minutes left",
          "Two people needed",
          "Two items required",
        ],
      };
    case '3':
      return {
        phrases: [
          "Three times",
          "Three ways",
          "Three days",
          "Three weeks",
          "Three hours",
          "Three steps",
          "Three options",
          "Three minutes",
          "Three people",
          "Three items",
        ],
        words: [
          "Three",
          "Third",
          "Triple",
          "Trio",
          "Trinity",
          "Triad",
          "Thrice",
          "Ternary",
          "Tertiary",
          "Triplet",
        ],
        daily: [
          "Three tasks",
          "Three meetings",
          "Three calls",
          "Three emails",
          "Three files",
          "Three reports",
          "Three updates",
          "Three checks",
          "Three reviews",
          "Three approvals",
        ],
        sentences: [
          "Three times faster",
          "Three ways to improve",
          "Three days deadline",
          "Three weeks project",
          "Three hours session",
          "Three steps process",
          "Three options to choose",
          "Three minutes warning",
          "Three people team",
          "Three items needed",
        ],
      };
    case '4':
      return {
        phrases: [
          "Four times",
          "Four ways",
          "Four days",
          "Four weeks",
          "Four hours",
          "Four steps",
          "Four options",
          "Four minutes",
          "Four people",
          "Four items",
        ],
        words: [
          "Four",
          "Fourth",
          "Quad",
          "Quartet",
          "Quadruple",
          "Square",
          "Quarter",
          "Quadrant",
          "Quart",
          "Foursome",
        ],
        daily: [
          "Four tasks",
          "Four meetings",
          "Four calls",
          "Four emails",
          "Four files",
          "Four reports",
          "Four updates",
          "Four checks",
          "Four reviews",
          "Four approvals",
        ],
        sentences: [
          "Four times stronger",
          "Four ways to succeed",
          "Four days remaining",
          "Four weeks duration",
          "Four hours workshop",
          "Four steps method",
          "Four options available",
          "Four minutes timer",
          "Four people group",
          "Four items list",
        ],
      };
    case '5':
      return {
        phrases: [
          "Five times",
          "Five ways",
          "Five days",
          "Five weeks",
          "Five hours",
          "Five steps",
          "Five options",
          "Five minutes",
          "Five people",
          "Five items",
        ],
        words: [
          "Five",
          "Fifth",
          "Quintet",
          "Quintuple",
          "Pentagon",
          "Pentad",
          "Quinary",
          "Quint",
          "Fiver",
          "Cinque",
        ],
        daily: [
          "Five tasks",
          "Five meetings",
          "Five calls",
          "Five emails",
          "Five files",
          "Five reports",
          "Five updates",
          "Five checks",
          "Five reviews",
          "Five approvals",
        ],
        sentences: [
          "Five times better",
          "Five ways to improve",
          "Five days work week",
          "Five weeks course",
          "Five hours training",
          "Five steps plan",
          "Five options to pick",
          "Five minutes break",
          "Five people team",
          "Five items checklist",
        ],
      };
    case '6':
      return {
        phrases: [
          "Six times",
          "Six ways",
          "Six days",
          "Six weeks",
          "Six hours",
          "Six steps",
          "Six options",
          "Six minutes",
          "Six people",
          "Six items",
        ],
        words: [
          "Six",
          "Sixth",
          "Sextet",
          "Hexagon",
          "Hexad",
          "Sextuple",
          "Senary",
          "Half dozen",
          "Sextant",
          "Hex",
        ],
        daily: [
          "Six tasks",
          "Six meetings",
          "Six calls",
          "Six emails",
          "Six files",
          "Six reports",
          "Six updates",
          "Six checks",
          "Six reviews",
          "Six approvals",
        ],
        sentences: [
          "Six times faster",
          "Six ways to solve",
          "Six days schedule",
          "Six weeks program",
          "Six hours session",
          "Six steps process",
          "Six options provided",
          "Six minutes left",
          "Six people required",
          "Six items needed",
        ],
      };
    case '7':
      return {
        phrases: [
          "Seven times",
          "Seven ways",
          "Seven days",
          "Seven weeks",
          "Seven hours",
          "Seven steps",
          "Seven options",
          "Seven minutes",
          "Seven people",
          "Seven items",
        ],
        words: [
          "Seven",
          "Seventh",
          "Septet",
          "Heptagon",
          "Heptad",
          "Septuple",
          "Septenary",
          "Week",
          "Hept",
          "Sept",
        ],
        daily: [
          "Seven tasks",
          "Seven meetings",
          "Seven calls",
          "Seven emails",
          "Seven files",
          "Seven reports",
          "Seven updates",
          "Seven checks",
          "Seven reviews",
          "Seven approvals",
        ],
        sentences: [
          "Seven times stronger",
          "Seven ways to improve",
          "Seven days a week",
          "Seven weeks course",
          "Seven hours work",
          "Seven steps method",
          "Seven options available",
          "Seven minutes warning",
          "Seven people team",
          "Seven items list",
        ],
      };
    case '8':
      return {
        phrases: [
          "Eight times",
          "Eight ways",
          "Eight days",
          "Eight weeks",
          "Eight hours",
          "Eight steps",
          "Eight options",
          "Eight minutes",
          "Eight people",
          "Eight items",
        ],
        words: [
          "Eight",
          "Eighth",
          "Octet",
          "Octagon",
          "Octad",
          "Octuple",
          "Octal",
          "Octave",
          "Oct",
          "Ogdoad",
        ],
        daily: [
          "Eight tasks",
          "Eight meetings",
          "Eight calls",
          "Eight emails",
          "Eight files",
          "Eight reports",
          "Eight updates",
          "Eight checks",
          "Eight reviews",
          "Eight approvals",
        ],
        sentences: [
          "Eight times better",
          "Eight ways to succeed",
          "Eight days remaining",
          "Eight weeks program",
          "Eight hours shift",
          "Eight steps process",
          "Eight options to choose",
          "Eight minutes timer",
          "Eight people group",
          "Eight items checklist",
        ],
      };
    case '9':
      return {
        phrases: [
          "Nine times",
          "Nine ways",
          "Nine days",
          "Nine weeks",
          "Nine hours",
          "Nine steps",
          "Nine options",
          "Nine minutes",
          "Nine people",
          "Nine items",
        ],
        words: [
          "Nine",
          "Ninth",
          "Nonet",
          "Enneagon",
          "Ennead",
          "Nonuple",
          "Nonary",
          "Novenary",
          "Niner",
          "Ennea",
        ],
        daily: [
          "Nine tasks",
          "Nine meetings",
          "Nine calls",
          "Nine emails",
          "Nine files",
          "Nine reports",
          "Nine updates",
          "Nine checks",
          "Nine reviews",
          "Nine approvals",
        ],
        sentences: [
          "Nine times faster",
          "Nine ways to improve",
          "Nine days deadline",
          "Nine weeks course",
          "Nine hours work",
          "Nine steps plan",
          "Nine options available",
          "Nine minutes left",
          "Nine people team",
          "Nine items needed",
        ],
      };
    default:
      return null;
  }
};


